### ISSUE TITLE
Parametric EQ support

### ISSUE THREAD

**Issue by JohnRTitor** [GanstaKingofSA/PA-CEQ#1]
Hi, from V906 Poweramp EQ supports parametric EQ. So would be nice if you could release PA-CEQ preset for parametric EQ, thanks. https://forum.powerampapp.com/topic/21506-poweramp-equalizer-build-899-906/

**Comment by GanstaKingofSA** [comment]
Hi. Thanks for the notice about this feature. 

Since PA-CEQ was originally made for the base Poweramp app, for a Parametric EQ release I would have to release it and mark it as a Poweramp Eq preset within PA-CEQ itself. Also since I normally do EQ testing on such things, it may take some time to get it right and to grasp the Parametric EQ waves if I decide some frequencies that aren't there should be added, etc. This is something I will work on though.

**Comment by JohnRTitor** [comment]
Hey thanks for willing to work on it mate. Parametric EQ just made its way to Poweramp EQ, so I assume it will be added to Poweramp in near future. Both PA and PEQ shares the same codebase, so I assume EQ preset made for PEQ would work like the same in the main app. Btw, I use PA-CEQ presets on PEQ and it's pretty cool :)

**Comment by GanstaKingofSA** [comment]
No worries. Right now I started transfering 2.1 to Parametric and I just noticed that this new EQ might have fixed a small issue with PA-CEQ before-hand on certain devices where the audio can distort at higher volumes. If that's the case then PA-CEQ can finally ditch the Apple DAC preset if needed once Max adds Parametric to the main Poweramp app.

**Comment by JohnRTitor** [comment]
Speaking of higher volumes, the volume seems very loud (even at normal level) when PA-CEQ is enabled, probably because of the high gain value of PA-CEQ. I would appreciate if you could specify a preamp value, normalising the audio I mean.

**Comment by GanstaKingofSA** [comment]
Gotcha. Thanks for the added note. Right now I think I got a OK testing version of Parametric which can still use some edits a bit but if you want to test that out, I can send it here to see for yourself.

**Comment by JohnRTitor** [comment]
Yeah cool, I can do some testing.

**Comment by GanstaKingofSA** [comment]
Alright. Here's a testing version I got for now. Gonna eat for the meantime but I should be back to do more once I'm done. https://drive.google.com/file/d/1LlvFDqikM_wxrlls21XpbStDinrBhOUY/view?usp=drivesdk

**Comment by JohnRTitor** [comment]
Yeah sure have a toast. I had a quick look at it and it sounds like there is slightly less treble and slightly more bass than in the 31 band graphic EQ preset? 🤔 And by the way you don't have to share screenshots of presets anymore. Just import the EQ preset from PEQ and share the file here. 
![IMG_20210629_223000](https://user-images.githubusercontent.com/50095635/123840390-e395d280-d92b-11eb-9d89-af67cfb9c83e.jpg)

**Comment by GanstaKingofSA** [comment]
Gotcha. Just a habit to screenshot since Poweramp is still needed. I'll take a look again at the values and get back with a 2nd build.

**Comment by GanstaKingofSA** [comment]
Also forgot to mention, is it still louder in this version of PA-CEQ or no?

**Comment by JohnRTitor** [comment]
> Also forgot to mention, is it still louder in this version of PA-CEQ or no?

I used a preamp of -2.0dB and it was fine.

**Comment by GanstaKingofSA** [comment]
Ah. Ok. Are you at 60% Volume or maxing it out?

**Comment by JohnRTitor** [comment]
Hey it's ok I just prefer a bit less loud sound with my in-ear earphones. 🤭 Currently at all 33% and it's all good. The sound is not that loud as it was with the 31band EQ. :)

**Comment by GanstaKingofSA** [comment]
I see. I'm just wanting to know more info for testing and see if the preamp could stick at 0 but adjust the EQ levels

**Comment by JohnRTitor** [comment]
> I see. I'm just wanting to know more info for testing and see if the preamp could stick at 0 but adjust the EQ levels

Hey the main use of preamp is to reduce the loudness to prevent distortion/clipping at high volume, make sure you have that covered. I don't really use very high volume so you'll have to check that on your own. I tuned the volume upto 50% and it's still fine.

**Comment by JohnRTitor** [comment]
You could drop a next build and Lemme check it again? How about that? 🤔

**Comment by GanstaKingofSA** [comment]
OK here's another test sample. It's a bit less loud than normal PA-CEQ 2.1 but I think it feels more optimal.
https://drive.google.com/file/d/1z64f1JEf1Qo3zCfkVzcOeg5Gsgzfuclp/view?usp=sharing

**Comment by JohnRTitor** [comment]
Sounds great, the bass is good too.

**Comment by GanstaKingofSA** [comment]
That's good to hear. I'll try to replicate it for normal Poweramp then but I guess if all is good here, then I can release it as such now under a different version name i.e PA-CEQ 2.2.

**Comment by GanstaKingofSA** [comment]
Thanks for your help. Closing this issue now.

**Comment by JohnRTitor** [comment]
![IMG_20210630_100002](https://user-images.githubusercontent.com/50095635/123902303-45852500-d98a-11eb-8d9b-a25a91539f85.jpg)

By the way, I forgot to ask you about this, which band overlap mode should I use with your EQ preset?

**Comment by GanstaKingofSA** [comment]
I never changed that part so it would be the default option when you turn on the EQ. Mine is set to Envelope.
