### ISSUE TITLE
Poweramp now has Parametric EQ

### ISSUE THREAD

**Issue by JohnRTitor** [GanstaKingofSA/PA-CEQ#2]
Hi in the last beta releases, parametric EQ have been implemented. I remember you said you made the Parametric EQ preset specifically for Poweramp EQ. I actually have been using it in Poweramp music player and it's pretty good! By the way, from now on exported preset of graphical EQ too would be nice, since both EQ and music player have import/export preset support.

**Comment by GanstaKingofSA** [comment]
Thanks for the heads up. The 3.0 JSON works in PA and now exported the graphic preset. Update 3.01 should be out in a few hours

**Comment by GanstaKingofSA** [comment]
PA-CEQ 3.01 is now out which adds the presets over to Poweramp and adds the Graphic EQ export file. Closing issue now.
